sidebase/nuxt-auth

src/runtime/composables/useSession.ts
When signIn function is used with id provider paramater it does not start the sign-in flow. The error is related with the CSRF request before sending POST to /signin endpoint.
=> Fix: Starts OAuth sign-in flow when clicked

README.md
This PR slightly changes the formulation of APP to universal-application and of API to server-api. It also adds links to the relevant Nuxt documentation.
=> docs: use universal instead of app

README.md, playground/app.vue, playground/pages/index.vue, playground/server/api/protected/inline.ts, playground/server/api/token.get.ts, playground/server/middleware/auth.ts, src/module.ts, src/runtime/composables/useSession.ts, src/runtime/server/services/index.ts, src/runtime/server/services/nuxtAuthHandler.ts
Closes https://github.com/sidebase/nuxt-auth/issues/20
This PR:
- adds server-side `getToken` helper to get the current, decoded JWT token, this is the equivalent of [getToken of nextauth](https://next-auth.js.org/tutorials/securing-pages-and-api-routes#using-gettoken)
- use `Parameters<typeof useFetch>[1]` to type `_fetch` params better
- better typing for `getProviders` and `signIn`: autocomplete of provider names
- stricter type checks in a couple of places
Checklist:
=> feat: add `getToken`

package-lock.json, package.json, src/runtime/server/services/nuxtAuthHandler.ts
Contributes to https://github.com/sidebase/nuxt-auth/issues/28
Hotfix:
- use `parseCookies` instead of undefined `useCookies`
- release `beta.7`
=> Hotfix use cookie and release beta.7

README.md, package-lock.json, package.json, playground/nuxt.config.ts, playground/pages/index.vue, playground/server/api/auth/[...].ts, src/runtime/composables/useSession.ts, src/runtime/server/services/nuxtAuthHandler.ts
Closes #21.
Contributes to #30 (security section added)
This PR introduces isomorphic session fetching. Getting this to work was quite tricky as regular `useFetch` cannot / should not be used in composables and methods, prompting vue warnings, see https://github.com/nuxt/framework/issues/1852#issuecomment-966161569
The solution was to:
- switch to `$fetch`
- write some utilities that produce correct urls, redirects, ... on the server- and the client-side
This PR also:
- makes the 2-provider credential example more realistic
- adds a basic security section
- adds a custom sign in page docs section
Checklist:
=> feat: make useSession isomorph :confetti:

playground/nuxt.config.ts, src/module.ts, src/runtime/server/services/nuxtAuthHandler.ts
To allow a clean `npm postinstall` step (that automatically happens on first nuxt install) we move the exception-check of an unset origin to the `runtime`
=> Move `origin` checking to runtime

package-lock.json, package.json
Release 0.1.2
This release:
- move `origin` check to runtime, to allow `npm run build` without problems when `origin` is unset
=> Release 0.1.2

src/runtime/server/services/nuxtAuthHandler.ts
Closes #52 .
We should overwrite the request-method to `GET` when `checkSessionOnNonAuthRequest` is `true`, as the `getServerSession` helper may also be called from non-GET requests. In those cases `NuxtAuth` would throw an error saying that the method is incorrect.
Checklist:
=> fix: always set method to `GET` for internal getServerSession requests

src/runtime/server/services/nuxtAuthHandler.ts
=> fix: always upper-case methods before passing them around or comparing them

src/module.ts
Closes https://github.com/sidebase/nuxt-auth/issues/62.
Checklist:
=> fix: create runtimeConfig in nuxt options if empty

src/module.ts
At the moment, the origin check is performed wrongly! This will actually stop deployment in production 👀
Workaround: Set it via `runtimeConfig.auth.origin`
Checklist:
=> fix: actually warn when origin is unset

src/runtime/composables/useSession.ts
See #74 for context.
Closes #74  .
Checklist:
=> fix: don't set `loading` to `true` on use `getSession`

package-lock.json, package.json
Release that brings `0.3.0` out of alpha 🎊 
This release also fixes a problem that https://github.com/nextauthjs/next-auth/pull/4769 introduced. We'll stay with fixed next-auth versions now to avoid this in the future.
=> release: 0.3.0

playground/app.vue, playground/pages/custom-signin.vue
Contributes to #88
This PR 
- adds an example custom sign in page as described by @sypx in #88. 
- manually tested out the described behavior on firefox and safari, both seem to work
=> feat(playground): add example custom sign in page

docs/content/3.application-side/3.custom-sign-in-page.md, playground/pages/custom-signin.vue, src/runtime/composables/useSession.ts
Closes #108
This PR:
- fixes `_fetch`  error behavior for `signIn` and `signOut`: Catch the error and retrieve its data to then analyze + return it to user instead of throwing 
- adds docs: custom sign in page error handling
- adds playground example: custom sign in with custom error handling
Checklist:
=> fix: catch errors and retrieve their data on signIn, signOut

docs/content/4.server-side/2.session-access-and-route-protection.md, docs/content/4.server-side/3.jwt-access.md, playground/app.vue
=> docs: improve getServerSession docs by showing how to pass along cookies during universal rendering

src/runtime/server/services/nuxtAuthHandler.ts
Closes issue of matijao#7025 on discord: https://discord.com/channels/1024643779711483944/1054873302138634331/1055871163173183518
This PR: Adds an initialization-attempt to the `getServerSession` utility, so that it doesn't fail in case no auth-endpoint was hit yet and thus the `nuxtAuthHandler` not being initialized yet.
=> Improve auth handler setup

src/runtime/composables/useSession.ts, src/runtime/middleware/auth.ts
This basically reverts commit 6e212540 as it was causing an issue with 05682549d3c80df9924a0c8f7f08793a07e631d7 which fixed the real middleware redirect issue.
But it keeps the improvements made for `navigateTo` util and the fix for `onUnauthenticated` of `getSession`
Checklist:
=> fix(middleware): redirect to signIn without using `location.replace`

.github/workflows/ci.yaml
This PR adds a smoke-test step that starts the playground and curls from it.
=> ci: add smoketest to start playground and curl from it

src/runtime/middleware/auth.ts
Closes #129
This PR augments the `PageMeta` interface to provide typing for the `auth`-key. Follows: https://nuxt.com/docs/guide/directory-structure/pages/#typing-custom-metadata
=> feat: provide type for disabling global auth middleware

docs/content/2.configuration/2.nuxt-config.md, playground/pages/signout.vue, src/module.ts, src/runtime/middleware/auth.ts
Closes #132
This PR:
- manually assembles a navigate to call, taking into account:
- the original target of the request for `callback`
- setting the correct `error` code for the sign-in page that is redirected to
- adds early 404 redirects to not enforce authentication for 404 pages per default
- adds a configuration option to change the aforementioned 404-behavior
This fully resolves the `ERR_HTTP_HEADERS_SENT` problem 🎊 It seems to be related to redirecting to a 404-page and may be the same as https://github.com/nuxt/framework/issues/9438. The problem will still occur when enforcing authentication for 404 pages by setting `allow404WithoutAuth: false`.
Checklist:
=> fix: do not use async composables in auth middleware

docs/content/2.configuration/3.nuxt-auth-handler.md
This PR adds a bit of additional information to the `NuxtAuthHandler` docs to make clearer that the filename must exactly be `[...].ts`. This is inspired by some docs-feedback on our discord: https://discord.gg/9MUHR8WT9B
=> docs: be clearer that catch-all name must be catch-all

package-lock.json, package.json
This PR resolves CVE-2022-46175 which is a critical security issue in `json5` that was reported by dependebot to us today:
CVE:  https://www.cve.org/CVERecord?id=CVE-2022-46175
=> security: resolve CVE-2022-46175

src/runtime/server/services/nuxtAuthHandler.ts
Closes #153
This PR:
- alters host detection to be in-line with what nextAuth expects: host AND path (so basically `NEXTAUTH_URL`)
- tested the login flow with credential and oauth providers -> works now
=> Fix base path

docs/content/2.configuration/2.nuxt-config.md, docs/content/3.application-side/4.protecting-pages.md, playground/nuxt.config.ts, playground/server/api/auth/[...].ts, src/module.ts, src/runtime/composables/useSession.ts, src/runtime/middleware/auth.ts, src/runtime/utils/fetch.ts, src/runtime/utils/url.ts
Closes #154
- add `defaultProvider`
- refactor `signIn` so that it is usable from application-side middleware's
- use `signIn` in application side middleware
=> Add `defaultProvider`

src/runtime/server/services/nuxtAuthHandler.ts
Closes #167 
This PR renames the default cookie names to `nuxt-auth.*`.
=> feat: use `nuxt-auth` and not `next-auth` as cookie name

docs/content/1.getting-started/2.installation.md, package-lock.json, package.json
Closes #128 
Closes #99 
Contributes to #117
This PR:
- makes `next-auth` a peer dependecy
- adds some documentation on the fact that `next-auth` is now a peer-dependency
=> Make next-auth peer dep

src/runtime/server/services/nuxtAuthHandler.ts
Reverts sidebase/nuxt-auth#176
Using a custom name forces us to also specify all other cookie options (read https://next-auth.js.org/configuration/options#cookies).
This may introduce security risks + will opt out some DX niceness (dynamic age values for development, ...), so we'll rever this change for now.
Re-opens #167
=> Revert "feat: use `nuxt-auth` and not `next-auth` as cookie name"

package-lock.json, package.json, src/runtime/server/services/nuxtAuthHandler.ts
Closes #169
Closes #151
This PR:
- bumps next-auth to 4.18.8
- ensures that `req` is still passed into handler in the correct format before update to `auth.js`
=> chore: bump next-auth to 4.18.8

package-lock.json, package.json, src/runtime/composables/useSession.ts, src/runtime/server/plugins/assertOrigin.ts, src/runtime/utils/fetch.ts
This PR:
- upgrades `nuxt-auth` to `nuxt@3.1.0`
- fixes related, new typing issues
- upgrades other nuxt / unjs ecosystem libraries
=> chore: upgrade major nuxt dep to 3.1, fix related ts issues

src/runtime/server/plugins/assertOrigin.ts
This PR changes & stubs the way we define our `assertOrigin` plugin to avoid:
```
ERROR  Error: Transform failed with 1 error:                                                                                                                                 nitro 15:53:09
/Users/nils/repos/sidebase/nuxt-auth/src/runtime/server/plugins/assertOrigin.ts:16:0: ERROR: Unexpected "}"
Unexpected "}"
```
See https://github.com/nuxt/nuxt/issues/18556 for more context.
=> fix: stub nitro plugin due to nuxt 3 upstream error

src/runtime/composables/useSession.ts, src/runtime/utils/fetch.ts
Closes #178
Closes #173
This PR tries to improve on the pesky "nuxt instance unavailable" problem (see https://github.com/nuxt/framework/issues/5740#issuecomment-1229197529):
- replaces most composable calls with wrapped `callWithNuxt` calls
- replaces all async composable calls with wrapped `callWithNuxt` calls
- 
Checklist:
=> fix: replace all async composable calls with callWithNuxt calls

playground/nuxt.config.ts, src/runtime/middleware/auth.ts
Closes #185
This PR: replaces the custom matching logic to the already existing one  of vue-router (big win).
This closes #185 as `vue-router` can correctly match dynamic urls like `/:language/protected` to `/de/protected`
=> fix: use `route.matched` to determine if 404 was hit

docs/content/1.getting-started/2.installation.md
This PR adds clearer documentation on when to install `next-auth` as a peer dependency.
=> docs: better instructions for peer dep for non-npm package managers

package-lock.json, package.json, playground/nuxt.config.ts, src/module.ts, src/runtime/composables/useSession.ts, src/runtime/server/services/nuxtAuthHandler.ts
Closes #220 
This PR makes nuxt-kit a full, direct dependency of the package. This was causing some issues for people using `pnpm`, see #220 for more context + a (rough) guess of why this is necessary now.
=> fix: make @nuxt/kit a direct dep

package-lock.json, package.json
Small release after 0.4.1 that:
- makes the peer-dep situtation clearer,
- adds nuxt/kit as a direct dep for `pnpm` users
=> release: 0.4.1-alpha.0

playground/pages/test/[slug].vue, src/runtime/server/services/nuxtAuthHandler.ts
Closes #241 
This PR adds a fix by @anPalmer introduced in https://github.com/sidebase/nuxt-auth/issues/241#issuecomment-1448663785.
The issue it fixes is that the API Endpoints sometimes returned the data incorrectly. @anPalmer then wrote a custom wrapper around `getServerSession()`, which seems to have fixed the issue. I integrated their changes into the core function in this PR.
Checklist:
=> Passed headers to `getServerSession`

docs/content/3.application-side/2.session-access-and-management.md
Fixes a documentation typo on https://sidebase.io/nuxt-auth/application-side/session-access-and-management
Checklist:
=> docs: fix property typo

docs/content/3.application-side/2.session-access-and-management.md
No ticket. Just something I found reading through the docs.
=> docs: fix typo in signIn

docs/README.md, docs/content/3.application-side/1.index.md, docs/content/4.server-side/1.index.md, docs/content/4.server-side/3.jwt-access.md
Figured I'd open a PR instead of an issue. See commits&changes, minor update to docs/urls.
Checklist:
=> Docs: Fix broken glossary links

README.md, docs/content/1.getting-started/1.index.md, docs/content/1.getting-started/3.quick-start.md, docs/content/3.application-side/1.index.md, docs/content/3.application-side/2.session-access-and-management.md, docs/content/3.application-side/3.custom-sign-in-page.md, docs/content/3.application-side/4.protecting-pages.md, docs/content/4.server-side/4.rest-api.md, docs/content/5.recipes/4.custom-session-data.md, docs/content/6.resources/4.prior-work.md, package-lock.json, package.json, playground/app.vue, playground/pages/custom-signin.vue, playground/pages/index.vue, playground/server/api/auth/[...].ts, src/module.ts, src/runtime/composables/useAuth.ts, src/runtime/composables/useAuthState.ts, src/runtime/middleware/auth.ts, src/runtime/plugin.ts, src/runtime/server/services/nuxtAuthHandler.ts
Closes #230  (again)
Closes https://github.com/sidebase/nuxt-auth/issues/157 (again)
This PR:
- renames `useSession` to `useAuth` in order to:
- leave `useSession` for the nuxt-native implementation (see issue #230)
- be future prove with future session library potenitally using this namespace (eg: https://github.com/sidebase/nuxt-session)
- upgrade deps:
- nuxt 3.3.3 -> minor
- defu 6.1.2 -> patch
- @nuxt/kit 3.3.3 -> minor
- ufo 1.1.1 -> minor
- nitro 2.3.2 -> minor
- next-auth 4.21.1 -> minor
- @nuxt/schema 3.3.3 -> minor
- ofetch 1.0.1 -> patch
- add deps for typescript:
- vue-tsc 1.2.0
- typescript 5.0.3
- (bump) @types/node to 18.15.11 -> minor
=> feat: Rename to use useAuth, upgrade deps

docs/content/1.getting-started/1.index.md, docs/content/1.getting-started/3.quick-start.md, docs/content/3.application-side/1.index.md, docs/content/3.application-side/2.session-access-and-management.md, docs/content/3.application-side/3.custom-sign-in-page.md, docs/content/3.application-side/4.protecting-pages.md, docs/content/3.application-side/5.guest-mode.md, docs/content/4.server-side/4.rest-api.md, docs/content/5.recipes/4.custom-session-data.md, docs/content/6.resources/4.prior-work.md
Closes #313
Changes made to the docs in d053e19 are not reflecting the stable version. Instead these breaking changes will be introduced in v0.5.0, which at the time of this commit is not stable but instead a release candidate. So instead i added info boxes to inform user about the upcoming renaming.
Closes # .
Checklist:
~~- replace "Closes " with "Contributes to" or other if this PR does not close the issue~~
=> docs: revert to useSession, add info about useAuth

docs/content/1.getting-started/1.index.md, docs/content/1.getting-started/3.quick-start.md, docs/content/3.application-side/1.index.md, docs/content/3.application-side/2.session-access-and-management.md, docs/content/3.application-side/3.custom-sign-in-page.md, docs/content/3.application-side/4.protecting-pages.md, docs/content/4.server-side/4.rest-api.md, docs/content/5.recipes/4.custom-session-data.md, docs/content/6.resources/4.prior-work.md
Followup to #318 right before release. Keeping some of its info-goodness.
=> docs: change official name from useSession to useAuth in docs, keep disclaimers for <=0.5 users

docs/content/3.application-side/5.guest-mode.md
Add `middleware: 'auth'` so that it becomes clear that the `auth` middleware has to be enabled for guest mode to work.
For me and some other people it was not clear that the middleware should also be added. So adding it to the example should make it clear enough.
Checklist:
=> Docs: improve guest mode example

src/runtime/composables/authjs/useAuth.ts
Closes #359.
Checklist:
For some reason, the function `joinPathToApiURLWN` returns `string` for client requests, and `Promise<string>` for SSR requests.
The user clicks on protected page.
No error.
The user goes to protected page.
It's a promise!
The server logs a Promise:
To fix this behavior, I've added an `await` keyword before the call for `joinPathToApiURLWN`.
=> fix: await for the joinPathToApiURLWN of signinUrl on authjs / useAuth / signIn() / (#359)

src/module.ts, src/runtime/composables/commonAuthState.ts, src/runtime/helpers.ts, src/runtime/server/services/authjs/nuxtAuthHandler.ts, src/runtime/server/services/utils.ts
=> fix: runtimeConfig access 'auth' property on top level warning

playground-local/app.vue, playground-local/nuxt.config.ts, playground-local/pages/login.vue, src/runtime/composables/commonAuthState.ts, src/runtime/middleware/auth.ts
=> fix: middleware, status was always 'loading', if no session was set

src/runtime/plugin.ts
This didn't work:
```ts
export default defineNuxtConfig({
auth: {
globalAppMiddleware: true // this doesn't work
},
})
```
because you needed to set `globalAppMiddleware` to
```ts
{
isEnabled: true
}
```
But the type also allows a boolean value.
=> fix: accept boolean value for `globalAppMiddleware` option

src/runtime/server/services/authjs/nuxtAuthHandler.ts
Other.
Next-auth GetTokenParams uses a generic R. It defaults to false. So if you want to use raw: true in the params it will error in typescript. This allows one to pass in the type they want for the raw param. To allow fetching the raw jwt instead of the decoded one.
Checklist:
=> Fix issue with getToken function and using raw: true in options. 

docs/content/3.application-side/4.protecting-pages.md, docs/content/v0.6/3.application-side/4.protecting-pages.md, src/runtime/middleware/auth.ts
Adds a `navigateUnauthenticatedTo` option to `definePageMeta()` to allow for overwriting the default behavior of redirecting to the login page
=> feat: protected route redirect overwrite per page

docs/content/3.application-side/2.session-access-and-management.md, docs/content/v0.6/3.application-side/2.session-access-and-management.md, src/runtime/composables/local/useAuth.ts, src/runtime/types.ts
Adds a `force` option to `getSession`. Useful when token cookie has been updated by an external api route (not handled by nuxt-auth's `signIn`/`signOut`) because the token in `useAuthState` would still be `undefined`/`null` after manually calling a register api route for example.
=> feat: getSession force refetch option

src/runtime/utils/url.ts
When the auth middleware is run, on the server using SSR, it redirects using the `sendRedirect` method from `h3`. This results in a redirect being sent along with the response, however the entire page is also executed on the server. 
This fix prevents that by returning abortNavigation after the redirect is sent, ensuring the protected page will not render.
One downside I've noticed is that this may log a 404 error, due to false having been returned from the middleware, but it seems to be the only way to actually stop navigation. Feedback on this is appreciated.
Here is a small reproduction of the principle as a generic Nuxt page:
```vue
<template>
<h1>test</h1>
</template>
<script setup lang="ts">
import {sendRedirect} from 'h3';
import {abortNavigation} from '#app';
definePageMeta({ …
```
=> fix: Abort SSR rendering on redirect

src/runtime/middleware/auth.ts, src/runtime/utils/url.ts
=> globalAppMiddleware: true behaves the same as globalAppMiddleware: { isEnabled: true }

src/runtime/composables/local/useAuth.ts
Closes #429
Due to the fact that we compose full URLs, when redirecting in the local provider, `navigateTo` throws an error, as it seems like we redirect to external URLs, as we use full urls and not relative ones. 
The easiest fix is to allow the local provider to redirect externally, which is what this PR does.
Checklist:
=> fix: `navigateTo` throws error on local provider 

docs/content/v0.6/2.configuration/2.nuxt-config.md, src/runtime/types.ts
Checklist:
This PR:
- Closes #546 
- Adds default (1800 per module) to documentation
- Fixes a couple of typos
=> Adds default & example to token.maxAgeInSeconds

docs/content/v0.6/2.configuration/2.nuxt-config.md, docs/content/v0.6/3.application-side/4.protecting-pages.md, src/runtime/middleware/auth.ts
Closes #410 
Ensures the `globalMiddleware` will not block the login page defined in the nuxt.config.
- If blocked, will lead to an endless redirect, between loginPage (gets Blocked) -> loginPage (gets Blocked) causing application to crash
- removes confussion, as the `globalMiddleware` does not block the default authjs login page
Checklist:
=> fix: Do not block the login page in `globalMiddleware`

package.json
This PR upgrades the version of nuxt-auth to 0.6.0 release candidate 0. This is the first production ready version of 0.6.0, which will now be tested in production on our internal projects, which will then be followed by a full release.
=> release: 0.6.0-rc.0

docs/content/v0.6/3.application-side/2.session-access-and-management.md, src/runtime/composables/local/useAuth.ts, src/runtime/types.ts
Closes #553 
You can now direct to an external url in the signin, signout and session methods:
```ts
signIn({ username, password }, { callbackUrl: 'https://sidebase.io', external: true })
```
Note: If this is set to true, then a hard page refresh will be done, therefore only set `external` to true, if you are really redirecting to a page outside of your application.
Checklist:
=> feat: Added option to set `callbackUrl` as external

docs/content/2.configuration/3.nuxt-auth-handler.md, docs/content/5.recipes/2.strapi.md, docs/content/5.recipes/6.laravel-passport.md, docs/content/5.recipes/7.vercel-deployment.md, docs/content/6.resources/5.errors.md
Makes it clearer how to set the `AUTH_ORIGIN`.
=> docs: Revisions of `0.6.0` docs

docs/content/1.getting-started/1.index.md, docs/content/1.getting-started/2.installation.md, docs/content/1.getting-started/3.quick-start.md, docs/content/2.configuration/1.index.md
Updates our docs to properly account for the new `refresh` provider.
Checklist:
=> docs: Finalized docs for `refresh` provider

SECURITY.md
Added a guide on how to report security issues, that should be handled internally. 
Checklist:
=> chore: Added security notice

docs/content/1.getting-started/3.quick-start.md
Fixes a minor typo in the quick start docs (`musst` -> `must`).
Checklist:
=> docs: fix typo in quick start

src/runtime/composables/refresh/useAuth.ts
Fix bug in refresh scheme feature (#581), avoiding a server fetch if `config.endpoints.signOut: false`  in configuration
=> [PR changes #393] fix: Add exclude signOut fetch if "config.endpoints.signOut = false"

src/runtime/composables/local/useAuth.ts, src/runtime/types.ts
Closes #614.
I'm glad to discuss further improvements.
@zoey-kaiser
=> feat: local provider prevent signIn flow

src/module.ts, src/runtime/plugins/refresh-token.server.ts
We currently apply some protections to help users avoid importing nitro in the vue part of the app and vice versa.
With https://github.com/nuxt/nuxt/pull/25162 we expanded the test cases (and now test for `server\/(api|routes|middleware|plugins)\/`).
We might relax this regexp (cc: @pi0) as it wasn't originally intended to catch module usage (it might be helpful to keep anyway!) but I spotted that your Nuxt server plugin was in the `server/` directory when I think it would more helpfully belong in the `plugins/` directory, mirroring a normal Nuxt project.
Checklist:
=> fix: move vue server plugin out of `server/` directory

src/runtime/middleware/auth.ts
=> feat: Add server check in middleware

playground-authjs/server/api/protected/inline.ts, playground-authjs/server/api/protected/middleware.ts, playground-authjs/server/api/token.get.ts, playground-authjs/server/middleware/auth.ts, playground-local/server/api/auth/login.post.ts, playground-local/server/api/auth/logout.post.ts, playground-local/server/api/auth/user.get.ts, playground-refresh/server/api/auth/login.post.ts, playground-refresh/server/api/auth/logout.post.ts, playground-refresh/server/api/auth/refresh.post.ts, playground-refresh/server/api/auth/user.get.ts, src/runtime/server/services/authjs/nuxtAuthHandler.ts
Fixes auto-imports missing after #665
Checklist:
=> fix: add missing imports

docs/content/1.getting-started/3.quick-start.md
Fix response body from `tokens` to `token` in quick-start docs in `local` and `refresh` providers.
As written in the nuxt-auth example codes, the correct return body is `token` instead of `tokens` as `tokens` gives `Error: Invalid reference token` error.
File References:
- https://github.com/sidebase/nuxt-auth-example/blob/add-local-provider/server/api/auth/login.post.ts
- https://github.com/sidebase/nuxt-auth/blob/main/playground-local/server/api/auth/login.post.ts
Checklist:
=> docs: fix response body for local provider

.github/ISSUE_TEMPLATE/enhancement.yml
Internal project managment
Updates the enhancement issue template to account for the fact we removed discussions.
=> chore: Update the issue templates

docs/content/3.application-side/5.guest-mode.md
I tried the guest middleware, it did not work (n redirect, no unauthenticatedOnly behaviour). Added the missing snippet, everything works like a charm. I think has been missed in the docs. You can try for yourself.
=> docs: Add missing middleware option for guestmode

docs/content/3.application-side/2.session-access-and-management.md
- [] 👌 Enhancement (improving an existing functionality like performance)
This pull request updates the documentation and enhances the `signUp` function within our authentication module. Specifically, it:
- Adds detailed comments to the `signUp` function examples to clearly explain each use case.
The aim is to provide clearer guidance for developers on how to use the `signUp` function effectively and to offer improved functionality that caters to a wider range of application scenarios.
- [] I have linked an issue or discussion.
=> docs: add docs for signUp (local povider)

.github/workflows/ci.yaml, .github/workflows/reproduire.yml, package.json, playground-local/.gitignore, playground-local/app.vue, playground-local/package.json, playground-local/playwright.config.ts, playground-local/tests/local.spec.ts, playground-local/vitest.config.ts, playground-refresh/.gitignore, playground-refresh/app.vue, playground-refresh/package.json, playground-refresh/playwright.config.ts, playground-refresh/tests/refresh.spec.ts, playground-refresh/vitest.config.ts, pnpm-lock.yaml
This PR adds Playwright E2E testing
=> test: add Playwright

src/runtime/server/services/authjs/nuxtAuthHandler.ts
Fix case where secureCookie is passed as false, and we need it to stay false 
in evaluation.  Use the nullish coalescing operator here to avoid calling into 
getServerOrigin(), which does not apply to our use case.
=> Evaluation of getToken secureCookies parameter does not work as intended

src/runtime/utils/fetch.ts
In some scenarios, the callWithNuxt function throws an error and is hard to track because it appears to be a nuxt fetch issue. I moved the one line into the try-catch block to make it easier to understand where the issue is coming from when looking through server logs.
=> feat(fetch): improve error handling

docs/content/2.configuration/2.nuxt-config.md, playground-refresh/nuxt.config.ts, src/module.ts, src/runtime/composables/refresh/useAuth.ts, src/runtime/helpers.ts, src/runtime/plugins/refresh-token.server.ts, src/runtime/types.ts
Closes #635 
This allows setting custom `refresh` request body to allow usages with external backends
=> feat(#635): allow changing refresh request body via json pointer

README.md, docs/content/1.getting-started/2.installation.md, docs/content/v0.5/1.getting-started/2.installation.md
This updates the documentation to use the [`nuxi module add` command](https://github.com/nuxt/cli/pull/197) which should simplify docs a bit and also improve user experience as there's no need to add to `nuxt.config` manually.
It's documented [here](https://nuxt.com/docs/api/commands/module#nuxi-module-add).
I may have missed a few spots in the documentation as I'm doing this across the modules ecosystem assisted by the power of regular expressions ✨, so I'd appreciate a review 🙏
=> docs: use new `nuxi module add` command in installation

src/runtime/composables/authjs/useAuth.ts, src/runtime/composables/commonAuthState.ts, src/runtime/composables/local/useAuthState.ts, src/runtime/types.ts, src/runtime/utils/url.ts
Closes #742 
This fixes `_fetch` usage, getting rid of internal HTTP calls being made to itself and properly using `$fetch`
=> enh(#742): optimize internal $fetch calls

src/runtime/composables/local/useAuth.ts, src/runtime/composables/refresh/useAuth.ts
https://github.com/sidebase/nuxt-auth/issues/411
When using method `signIn(credentials, { callbackUrl: '/' })` method with `local` or `refresh` provider, the `callbackUrl` and other options were sent to the server.  
As mentioned in https://github.com/sidebase/nuxt-auth/issues/411#issuecomment-1612376120, some servers can reject the request if the payload contains invalid parameters.
Those options are only used when the sign-in request is done, they shouldn't be sent to the server. They can be set directly in `credentials` data if they have to.
Flagged as _breaking change_ because some options may have to be copied from `signInOptions` to `credentials`.
=> fix: don't send sign-in options in request payload

docs/content/2.configuration/2.nuxt-config.md, docs/content/2.configuration/5.session-config.md
- add a session-config.md to better document application-side session handling
- update nuxt-config.md to match the new types
As mentioned in PR #715 the session config needs some love. This PR tries to give the developer a better understanding on how the package handles the session refresh.
=> 📝 docs: add session config.md

src/runtime/server/services/authjs/nuxtAuthHandler.ts
https://github.com/nuxt-modules/i18n/issues/2980
sendRedirect returns a promise and should be awaited
I have nuxt i18n that sets a cookie, but there is a conflict if await is not used.
I have patched this locally and the cookie specific error was gone.
=> fix: await sendRedirect in auth handler

src/runtime/composables/local/useAuthState.ts
Conditionally register onMounted within useAuthState to fix these warnings: 
```
onMounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup().
```
=> fix: Added getCurrentInstance check to conditionally register onMounted in useAuthState.

src/runtime/composables/local/useAuth.ts, src/runtime/types.ts
https://github.com/sidebase/nuxt-auth/issues/761
The linked issue just covered half of the problem ; in the current form, `getSession` cannot be disabled, even with a configuration extracted [from the documentation](https://sidebase.io/nuxt-auth/getting-started/quick-start#provider-local) such as:
```js
{
auth: {
baseURL: '/api/auth',
provider: {
type: 'local',
endpoints: {
getSession: false,
}
}
}
}
```
It's not an issue while you're not calling it, except that it is called by [`signIn` anyways](https://github.com/sidebase/nuxt-auth/blob/faa039b72da2c64d9c214f0502dea053c7a4ff84/src/runtime/composables/local/useAuth.ts#L35), at least with the `local` and `refresh` providers. Eventually, it means that an unexpected HTTP request is sent, which on one hand is inefficient, and on the other …
=> fix: properly disable `getSession` endpoint for local and refresh

docs/.vitepress/config.mts, docs/guide/application-side/session-access.md, docs/guide/local/quick-start.md
closes #782
Adds an explanation to the docs on how to properly set external backend URLs for the `local` and `refresh` providers, based on the outline by @coreyshuman in https://github.com/sidebase/nuxt-auth/issues/782#issuecomment-2223861422 ❤️
=> docs(#782): guide on using external urls in endpoints

docs/guide/local/quick-start.md
related to #802
Fixes a small error in the docs, properly wraps `endpoints` in the `provider` option for external backend docs on local / refresh
=> docs(#802): wrap endpoints in provider to match nuxt.config.ts

docs/guide/application-side/session-access.md, docs/guide/getting-started/choose-provider.md
=> docs: fix provider table and made docs more gender-neutral

src/runtime/middleware/auth.ts
=> fix(#792): do not block login page for refresh provider

.github/workflows/ci.yaml, .github/workflows/deploy-docs.yml, .npmrc, docs/package.json, package.json, playground-authjs/nuxt.config.ts, playground-authjs/package.json, playground-local/nuxt.config.ts, playground-local/package.json, playground-refresh/nuxt.config.ts, playground-refresh/package.json, pnpm-lock.yaml
Migrate to PNPM 9 and update dependencies
=> chore: update dependencies and use pnpm 9

src/runtime/server/services/authjs/nuxtAuthHandler.ts
Potentially closes #808
After being redirected to the login page, the URL looks like this: `http://localhost:3000/login?callbackUrl=http://localhost:3000/dashboard&error=undefined`
The error query parameter is undefined, and I would like to change this to a specific error message or remove it altogether.
We wrap the `error` heading in `String()` and add a fallback to `undefined` if it does not exist. However, transferring an error to a string will always result in it being set, as the wrapper undefined in string results in a string that is undefined, which lines up with the path generated!
=> fix(#808): only add error to response when it is set

docs/guide/local/quick-start.md, src/module.ts, src/runtime/composables/local/useAuthState.ts, src/runtime/composables/refresh/useAuthState.ts, src/runtime/types.ts
Added httpOnly attribute support for local and refresh providers + updated the docs accordingly
=> feat: Add httpOnly cookie attribute support

src/runtime/utils/refreshHandler.ts
#834 
The enableOnWindowFocus feature should not be triggered on pages that are accessible to unauthenticated users. Currently, when a user switches back to a tab containing an unauthenticated page (such as the login page of us), the refresh mechanism is still executed, which is unnecessary and potentially problematic.
This pull request addresses that issue by ensuring that the enableOnWindowFocus feature is only executed when the user is in an authenticated state. This change prevents unnecessary refreshes on unauthenticated pages and eliminates potential problems associated with triggering the refresh mechanism on pages accessible to unauthenticated users.
=> fix(#834): Do not refresh on window focus for unprotected pages

package.json
N/A
This adds 'description', 'homepage', 'repository' metadata fields to `package.json` to be used by e.g `npm` or `renovate`.
**npm:** Open https://www.npmjs.com/package/@sidebase/nuxt-auth and you won't find 'Homepage' or 'Repository' as below
**renovate:** Notice other packages are clickable links and have 'source' which opens its repository, unlike @sidebase/nuxt-auth
=> chore: add metadata fields to package.json

README.md, docs/.vitepress/routes/navbar.ts, docs/.vitepress/routes/sidebar/guide.ts, docs/.vitepress/routes/sidebar/index.ts, docs/.vitepress/routes/sidebar/upgrade.ts, docs/.vitepress/theme/components/Layout.vue, docs/guide/advanced/deployment/self-hosted.md, docs/guide/application-side/configuration.md, docs/guide/application-side/session-access.md, docs/guide/getting-started/choose-provider.md, docs/guide/local/quick-start.md, docs/upgrade/index.md, docs/upgrade/version-0.8.0.md, docs/upgrade/version-0.9.0.md, playground-local/app.vue
=> chore: update docs for `0.9.0`

docs/upgrade/version-0.9.0.md
=> docs: add 0.9.0 changelog

package.json
Not Applicable
This PR explicitly denies violations of [`no-unused-vars`](https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-unused-vars.html) for oxlint.
We are planning on bringing [`no-unused-vars`](https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-unused-vars.html) out of our nursery category and making it a correctness rule in the near future. This PR will help ensure this does not break your CI. Thank you for using oxlint.
> _note: I am the product manager for oxlint_
=> chore: prepare lint script for no-unused-vars

src/runtime/utils/url.ts
This PR fixes a long-lasting bug. On first redirect from a protected pages to the login page using the `authjs` provider, you would often get the following message in the console:
```
[nuxt] [request error] [unhandled] [500] Cannot set headers after they are sent to the client
```
This issue originates from the problem of how do we set a redirect inside the SSR context if the page is protected. Until now we used a outdated workaround from [Nuxt](https://github.com/nuxt/framework/blob/ab2456c295fc8c7609a7ef7ca1e47def5d087e87/packages/nuxt/src/app/composables/router.ts#L97-L115). I did some digging and managed to find a better solution [here](https://github.com/nuxt/nuxt/blob/d188542a35bb541c7ed2e4502c687c2132979882/packages/nuxt/src/app/composables/router.ts#L161-L188).
In the old version …
=> fix: cannot set headers after they are sent to the client

docs/guide/authjs/nuxt-auth-handler.md
Closes #897
This clarifies that using a provider in `next-auth@4` with Vite requires a `.default` workaround.
=> docs(#897): clarify `authjs` providers usage (next-auth@4)

docs/guide/local/session-data.md
https://github.com/sidebase/nuxt-auth/pull/592 moved the location of the `sessionDataType` in the configuration, but this seemingly never made it into the docs ;-)
https://github.com/sidebase/nuxt-auth/pull/592
=> docs: correct location of session data type definitions

docs/guide/application-side/configuration.md, docs/resources/error-reference.md
Closes #906
This clarifies how the origin is determined and how `originEnvKey` works.
=> docs(#906): clarify `origin` documentation

.github/workflows/ci.yaml, playground-local/app.vue, playground-local/config/AuthRefreshHandler.ts, playground-local/nuxt.config.ts, playground-local/server/api/auth/login.post.ts, playground-local/server/api/auth/refresh.post.ts, playground-local/server/api/auth/user.get.ts
This provides an implementation of refresh functionality to `playground-local`.
The benefits are:
- we can start E2E testing refresh logic again (which was dropped after #822);
- the implementation is closer to what developers do rather than being a stub.
=> enh: provide a demo implementation of refresh provider

src/runtime/composables/local/useAuth.ts, src/runtime/middleware/auth.ts
#861 
Add functionality redirect user back to requested page after authentication
Added a redirect query parameter to auth middleware navigateTo when a guest visits authenicated page.
This will help users redirect back to previous page after sign in.
Currently when guest tries to access a protected page they are redirected to `/login` page and after login they are redirect to default `callbackUrl `unless they specify `callbackUrl` in the `signIn` function.
This feature will help automatically redirect a user back to the page they requested after login. For example, if they requested to access `'/profile'` and they are redirected to login page, after successful login, they will be redirected back to `'/profile'`. They can also override this by providing a `callbackUrl `in the signIn …
=> enh(#861): Redirect back to requested page after authentication

playground-authjs/server/api/auth/[...].ts, src/runtime/composables/commonAuthState.ts, src/runtime/composables/local/useAuth.ts, src/runtime/middleware/auth.ts, src/runtime/plugins/refresh-token.server.ts, src/runtime/server/services/authjs/nuxtAuthHandler.ts
This PR fixes violations of `eslint/no-else-return`, a rule we have just ported into oxlint.  This is part of our effort to keep our [ecosystem CI tests](https://github.com/oxc-project/oxlint-ecosystem-ci) green. Thank you for using oxlint ⚓
=> fix: violations of upcoming `eslint/no-else-return` oxlint rule

docs/guide/local/quick-start.md, playground-local/nuxt.config.ts, src/module.ts, src/runtime/composables/local/useAuth.ts, src/runtime/plugins/refresh-token.server.ts, src/runtime/types.ts
#895
Added `refreshResponseTokenPointer` option to allow the token assignment (during the `refresh` call) to a different property respect to the `signIn` call.
This is useful in cases where the server returns the token in a property with different names between `login` and `refresh`.
=> enh(#895): Custom refresh response token pointer

docs/guide/getting-started/installation.md
~~… as regular dep~~
~~@sidebase/nuxt-auth should be installed as a regular dependency instead of a dev dependency.~~ Also added additional scripts for yarn and pnpm
~~`@sidebase/nuxt-auth` should be installed as a regular dependecy instead of dev dependency.~~ Also added pnpm and yarn script variants of `npx nuxi@latest module add sidebase-auth`
=> docs: update installation.md

docs/.vitepress/routes/navbar.ts, docs/.vitepress/routes/sidebar/guide.ts, docs/.vitepress/routes/sidebar/upgrade.ts, docs/.vitepress/theme/components/Layout.vue, docs/guide/advanced/url-resolutions.md, docs/guide/application-side/configuration.md, docs/guide/local/quick-start.md, docs/upgrade/index.md, docs/upgrade/version-0.10.0.md
=> doc: adjust docs for the 0.10.0 release

docs/upgrade/version-0.10.0.md, package.json
=> release: 0.10.0

src/runtime/composables/local/useAuth.ts, src/runtime/types.ts
#967 
Documentation states that `signUp` endpoint may be disabled by setting it to `false`:
https://github.com/sidebase/nuxt-auth/blob/8d31537f51b14d90a4a7d703e83cb7e45f9b66c2/docs/guide/local/quick-start.md?plain=1#L54-L67
But if you try to do this, you will get the following typescript error in your IDE:
```
Type 'false' has no properties in common with type '{ path?: string | undefined; method?: "head" | "get" | "patch" | "post" | "put" | "delete" | "connect" | "options" | "trace" | undefined; }'. ts(2559)
```
And the case where `signUp` endpoint is disabled is not handled by the `signUp` function of the `useAuth` composable:
https://github.com/sidebase/nuxt-auth/blob/8d31537f51b14d90a4a7d703e83cb7e45f9b66c2/src/runtime/composables/local/useAuth.ts#L164-L178
This PR should fix these …
=> fix(#967): allow `signUp` endpoint to be disabled

src/runtime/composables/local/useAuth.ts
#978 
Only when redirect is true process the callback url because it is not used when redirect is false.
=> feat(local): ⚡ only process signIn callback url when redirect true

src/runtime/composables/authjs/utils/navigateToAuthPage.ts
Closes #970
This makes `navigateToAuthPage` implementation closer to that of Nuxt itself. It should help resolve some redirecting issues.
=> fix(#970): make redirect implementation match Nuxt's

src/runtime/server/services/authjs/nuxtAuthHandler.ts
Closes #984
This PR changes the path parameters being provided to `AuthJs`, namely:
- `basePath` is now exactly calculated `baseURL` instead of a static `/api/auth` which allows to use custom path like `/aax4/api/auth` (see #984);
- `RequestInternal.host` now has the full URL instead of simply origin because of [the way `AuthJs` parses URLs passed to it](https://github.com/nextauthjs/next-auth/blob/a26bb060e78a928e7725ca11eaf9aab317328549/packages/next-auth/src/utils/parse-url.ts#L15-L36).
=> fix(#984): allow custom endpoint subpaths for authjs

src/runtime/types.ts
Fix Typos in types.ts (JSdoc annotations & comment)
=> fix(docs): typos in types.ts

playground-authjs/pages/custom-signin.vue, playground-local/pages/protected/locally.vue, playground-local/pages/register.vue, playground-local/tests/local.spec.ts, src/runtime/composables/authjs/useAuth.ts, src/runtime/composables/local/useAuth.ts, src/runtime/types.ts
This moves all `useAuth` functions into their respective composables for better handling of context.
> [!WARNING]
> There's a breaking change in `local` provider `signUp` function which now only accepts 2 parameters. This is due to `signUp` having an [extra parameter](https://github.com/sidebase/nuxt-auth/blob/4b3a5904c9e0d3bce6a6334bf4a463d4835d4a48/src/runtime/composables/local/useAuth.ts#L170) from its initial implementation.
=> chore: refactor useAuth composables to encapsulate context

docs/.vitepress/routes/navbar.ts, docs/.vitepress/routes/sidebar/upgrade.ts, docs/upgrade/index.md, docs/upgrade/version-1.0.md
This updates the documentation to include the 1.0 Release Candidate
=> docs: update documentation to 1.0.0

docs/guide/application-side/session-access.md
Update docs to reflect breaking changes in `signUp` function's now-removed third parameter.
#1034
=> docs: Update session-access.md

docs/guide/authjs/nuxt-auth-handler.md
N/A
This clarifies some usage of adapters inside NuxtAuthHandler.
=> docs: add documentation about AuthJS adapters
