- .github/workflows/ci.yaml
- package-lock.json
- package.json
- playground/nuxt.config.ts
- src/module.ts
- src/runtime/server/api/auth.ts
> start to generate imports, be clearer in docs of `module.ts`

- package-lock.json
- package.json
> release: 0.0.1-beta.3

- README.md
- playground/pages/index.vue
> fix: docs ordering, call in onClick

- package-lock.json
- package.json
> release: 0.0.1-beta.4

- package.json
> release: 0.0.1-beta.5

- playground/server/middleware/auth.ts
- src/module.ts
- src/runtime/composables/useSession.ts
- src/runtime/server/services/nuxtAuthHandler.ts
This PR improves typing by:
-  removing a manual useFetch interface declaration,
- doing stricter checks in some places
> feat: improve types by re-using useFetch

- package-lock.json
- package.json
Release includes:
- `getToken`
- docs improvements
- TS improvements for provider-autocomplete
See more in release notes: TBD
> release: 0.0.1-beta.6

- package-lock.json
- package.json
Release 0.1.0
With `useSession` being fully isomorph, we should be ready for the first non-beta release 🎊
> release: 0.1.0

- README.md
- playground/pages/index.vue
- playground/pages/signout.vue
- src/runtime/composables/useSession.ts
> feat: add callback url on signout + document it

- src/runtime/composables/useSession.ts
Closes #37
Checklist:
- [x ] attached screenshots / screenshot not applicable
> fix: session and data types

- package-lock.json
- package.json
Changes:
- feat: support `callbackUrl` in `signOut`
- fix: types for `data` and `status`
> release: 0.1.1

- src/runtime/composables/useSession.ts
> fix: sign in options inherit from Record

- README.md
> docs: expand custom sign in page docs

- package-lock.json
- package.json
release 0.1.3 🎊 
see release notes for more (:
> release: 0.1.3

- README.md
Contributes to #30 
Checklist:
> fix(docs): port typo

- .eslintrc
- package-lock.json
- package.json
- playground/nuxt.config.ts
- playground/server/api/auth/[...].ts
- src/module.ts
> feat: upgrade to nuxt stable, upgrade minor deps as well

- package-lock.json
- package.json
> release: 0.2.0

- package-lock.json
- package.json
Release 0.2.1 with a bunch of doc changes + a fix for production deployments by @manniL ❤️ 
Full release notes here: https://github.com/sidebase/nuxt-auth/releases
> release: 0.2.1

- package-lock.json
- package.json
release 0.3.0-alpha.1, checkout if the new sync session works out.
> release: 0.3.0-alpha.1

- package-lock.json
- package.json
Release to hotfix "nuxt instance is not defined" problem via #77
> release: 0.3.0-alpha.2

- package-lock.json
- package.json
> release: 0.3.0-alpha.3

- package-lock.json
- package.json
> fix: use exact nextauth version to avoid breaking change

- README.md
> feat(docs): cleanup readme, dont repeat same claim multiple times

- docs/content/1.getting-started/1.index.md
Closes https://github.com/sidebase/docs/issues/35
Checklist:
> fix: finish intro sentence

- docs/content/1.getting-started/3.quick-start.md
- docs/content/2.configuration/3.nuxt-auth-handler.md
- docs/content/5.recipes/2.strapi.md
- docs/content/5.recipes/3.directus.md
- playground/server/api/auth/[...].ts
> feat(docs): improve .default ts ignore by replacing it with ts expect error

- src/runtime/composables/useSession.ts
- src/runtime/composables/useSessionState.ts
Add types `UseSessionReturn` and `UseSessionStateReturn`
Closes #112 
Checklist:
> fix: use type `Session` from `next-auth`

- docs/content/1.getting-started/1.index.md
> feat(docs): state more clearly that this lib is for non-static libraries, state more clearly that nextuath ressources can be used

- package-lock.json
- package.json
This PR updates minor dependencies.
> chore: update deps nuxt/kit and defu

- package-lock.json
- package.json
This PR releases 0.3.4 which fixes the `basePath` detection behavior.
> release: 0.3.4

- src/runtime/server/services/nuxtAuthHandler.ts
Closes #186.
Checklist:
---
I had someone come into my Discord asking for help with this so thought I'd push up a fix. Probably want to check it doesn't break anything
> fix(getServerSession): avoid infinite middleware stack

- README.md
> Fixed Discord invite link in Readme

- docs/content/_dir.yml
> Fixed Docs Layout

- docs/content/5.recipes/4.custom-session-data.md
Updating the custom session data recipe documentation based on #148
Closes #148 .
Checklist:
> Documentation update: Update 4.custom-session-data.md

- package.json
Releases version 0.4.2 with PR change #237
> Release 0.4.2

- docs/content/6.resources/0.index
This PR is needed to ensure our new redirects work correctly
> docs: added index page to resources

- package-lock.json
- package.json
test it with:
```sh
npm i -D @sidebase?nuxt-auth@0.4.3-alpha.1
```
Tested it in:
- Local
- https://nuxt-auth-example.sidebase.io (https://github.com/sidebase/nuxt-auth-example/pull/25)
> release: 0.4.3

- docs/content/5.recipes/6.laravel-passport.md
6.laravel-passport.md
Correct typos fixed
Closes #322 .
Checklist:
> fix: Correct typos fixed

- package.json
Release 0.5.0 -> release notes in "releases" section as usual.
> release: 0.5.0

- package.json
> release: 0.6.0-alpha.0

- package.json
> release: 0.6.0-alpha.1

- docs/content/5.recipes/8.azure-ad-example.md
adds a  azure AD NuxtAuthHandler example to recipes documentation section.
> docs: add azure AD example

- package.json
> release: 0.6.0-alpha.2

- docs/content/3.application-side/4.protecting-pages.md
- docs/content/v0.6/3.application-side/4.protecting-pages.md
- src/runtime/utils/url.ts
A small commit to fix misspellings of immeadiatly. This should not have any change around the app as I have only changed text in docs and JSDoc. So it could be fixed immeadiatly and doesn't need tests :D
Checklist:
> Fix mispellings of "immediately".

- docs/content/2.configuration/2.nuxt-config.md
- docs/content/v0.6/2.configuration/2.nuxt-config.md
The previous line didn't address the different ports used by HTTP vs HTTPS
> Make HTTP vs HTTPS port default clear

- src/runtime/composables/local/useAuth.ts
> fix: #356 - Extend/change local signIn credentials type

- src/module.ts
- src/runtime/plugin.ts
Closes #157.
Checklist:
Generated types `.nuxt/types/middleware.d.ts`
> fix: Autocomplete for 'auth' middleware in definePageMeta

- docs/content/v0.6/3.application-side/2.session-access-and-management.md
This PR: cleans up the v0.6 docs of session access and management.
Followup to https://github.com/sidebase/nuxt-auth/pull/375#pullrequestreview-1422886019
> docs: improve v0.6 session acccess and management

- package.json
> release: 0.6.0-beta.2

- src/runtime/middleware/auth.ts
> fix: definePageMeta auth option type

- docs/content/v0.6/_dir.yml
> hotfix: Fixed aisde level for 0.6 docs

- docs/content/2.configuration/3.nuxt-auth-handler.md
> docs: Made NextAuth Link to NextAuthHandler more visable

- src/runtime/server/services/utils.ts
> fix: runtimeConfig `auth` key access

- package.json
> release: 0.6.0-beta.3

- docs/content/v0.6/1.getting-started/3.quick-start.md
Closes #456
This PR fixes some dead links in the docs
> docs(fix): dead links

- docs/content/v0.6/6.resources/6.nuxt-security
Closes # .
Thanks to @tmlmt for bringing this solution in https://github.com/sidebase/nuxt-auth/issues/324
Checklist:
> docs: Add resouce on how to integrate nuxt-security

- package.json
> release: 0.6.0-beta.7

- docs/content/v0.6/3.application-side/2.session-access-and-management.md
- package.json
Updated version to `0.6.0-rc.1` to include the newest fixes to make 0.6.0 release ready 🥳
> release: `0.6.0-rc.1`

- docs/content/1.getting-started/1.index.md
- docs/content/3.application-side/2.session-access-and-management.md
- docs/content/v0.5/1.getting-started/2.installation.md
> docs: Last fixes to 0.6.0 docs

- package.json
Updated `package.json` version to 0.6.0 in preparation for final release!
> release: 0.6.0

- package.json
Updated the package version to 0.6.1 for the next update!
> release: 0.6.1

- package.json
Updates the package version to 0.6.2
> release: 0.6.2

- docs/content/2.configuration/3.nuxt-auth-handler.md
- docs/content/v0.5/2.configuration/3.nuxt-auth-handler.md
https://next-auth.js.org/adapters/overview now is 404, so replace it with new [url](https://authjs.dev/getting-started/adapters)
Checklist:
-----
<a href="https://stackblitz.com/~/github/kongmoumou/nuxt-auth/tree/kongmoumou%2Fpatch-64838"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz Codeflow" align="left" width="103" height="20"></a> _Submitted with [StackBlitz Codeflow](https://stackblitz.com/~/github/kongmoumou/nuxt-auth/tree/kongmoumou%2Fpatch-64838)._
> fix: update url

- package.json
> release: 0.6.4

- package.json
> release: 0.6.5

- src/runtime/middleware/auth.ts
> fix: include hash & query parameters in callbackUrl

- package.json
> release: 0.6.6

- .github/reproduire/needs-reproduction.md
- .github/workflows/reproduire-close.yml
- .github/workflows/reproduire.yml
> chore: Add reproduction workflow

- src/runtime/server/services/authjs/nuxtAuthHandler.ts
> fix(#523): deduplicate `appendHeader` in auth handler

- .github/workflows/reproduire-close.yml
> chore: fix reproduire label name

- package.json
> release: 0.7.0-rc.0

- package.json
> release: 0.7.0

- docs/content/1.getting-started/2.installation.md
Adjusts the recommended NextAuth version from `4.22` to `4.21.1`, as this version works more stabiliy with our module.
> docs: Adjusted Recommended NextAuth Version

- package.json
> release: 0.8.0-alpha.1

- package.json
> release: 0.8.0-alpha.2

- docs/content/1.getting-started/3.quick-start.md
- docs/content/1.getting-started/5.getting-help.md
- docs/content/2.configuration/2.nuxt-config.md
- docs/content/3.application-side/3.custom-sign-in-page.md
- docs/content/4.server-side/2.session-access-and-route-protection.md
- docs/content/5.recipes/1.index.md
Fixed some broken links and made some minor wording changes.
> docs: fix broken links and minor rewording

- docs/content/2.configuration/2.nuxt-config.md
- docs/content/2.configuration/5.session-config.md
- package.json
- playground-local/nuxt.config.ts
- playground-refresh/config/AuthRefreshHandler.ts
- playground-refresh/nuxt.config.ts
- playground-refresh/package.json
- pnpm-lock.yaml
- src/module.ts
- src/runtime/composables/authjs/useAuth.ts
- src/runtime/composables/local/useAuth.ts
- src/runtime/composables/refresh/useAuth.ts
- src/runtime/plugin.ts
- src/runtime/types.ts
- src/runtime/utils/refreshHandler.ts
#765
In #715 we introduced custom refresh handlers. Here I improve on it, introduce `refresh` function to `CommonUseAuthReturn` and properly use it for `refresh` handler.
> enh(#765): refactor `refreshHandler` and session refreshing; fix refresh provider refreshing

- package.json
> release: 0.8.0-alpha.3

- package.json
> release: 0.8.0-rc.1

- package.json
> release: 0.8.0

- docs/guide/local/quick-start.md
#782
A leftover type from #796
> docs: fix typo in external endpoints

- package.json
> release: 0.8.1

- docs/guide/advanced/deployment/self-hosted.md
> docs: fix typo in self-hosted deployment guide

- docs/guide/application-side/configuration.md
`globalAppMiddleware` should be second level title instead of 3rd level title.
> fix(docs): title hierarchy in app configuration

- .github/workflows/pkg.pr.new.yml
> fix: remove concurrency check from `pkg.pr.new` workflow

- docs/guide/authjs/custom-pages.md
The error page example has a typo in the script section.
https://github.com/sidebase/nuxt-auth/issues/893
> docs: Fix typo in custom-pages.md

- src/runtime/composables/local/useAuthState.ts
Closes #896
This sets a default value for `rawRefreshToken` which was not set due to a conditional.
> fix(#896): set rawRefreshToken default value

- package.json
> release: 0.9.2

- docs/recipes/community/laravel-passport.md
> docs: laravel-passport.md fix "Learn more" issue link 

- docs/.vitepress/routes/navbar.ts
- package.json
> release: 0.9.4

- package.json
> release: 0.10.0-rc.1

- package.json
> release: 0.10.0-rc.2

- package.json
> release: 0.10.1-alpha.1

- docs/guide/application-side/configuration.md
> docs: fix update default value for enablePeriodically to false

- .github/CONTRIBUTING.md
> docs: fix typos in contributing guide

- playground-local/pages/register.vue
None
Display the actual error message when registering account in local playground project.
> chore: display register error message

- docs/recipes/community/laravel-passport.md
- docs/recipes/community/strapi.md
- package.json
- playground-authjs/package.json
- playground-local/package.json
- pnpm-lock.yaml
- src/runtime/types.ts
This updates the dependencies in order to resolve several dependency advisories
> chore: bump dependencies

- docs/guide/advanced/url-resolutions.md
Everything in `nuxt.config.js` is bundled at `build` or `generate`. It stays fixed on runtime.
> docs(1044): correction of base url documentation

- docs/.vitepress/theme/components/Layout.vue
- package.json
> release: 1.0.1
